# Application configuration
spring.application.name=movie-review-api
server.port=8080

# Database Connection (MySQL)
# We use createDatabaseIfNotExist=true so MySQL creates 'movie_db' for us automatically
spring.datasource.url=jdbc:mysql://localhost:3306/movie_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Rishi123*

# Hibernate Configuration
# 'update' tells Hibernate to automatically create or update our database tables based on our Java Entities
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console (helpful for debugging and learning!)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# JWT Security Configuration
# This is our secret key. It should be at least 256 bits (32 characters) long.
# In a real app, you would never put this in the code! You'd use Environment Variables.
jwt.secret=MySuperSecretKeyForMovieReviewApiWhichNeedsToBeVeryLongAndSecure!
jwt.expirationMs=86400000 
# 86400000 milliseconds = 24 hours
